name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  GOPROXY: direct

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
      - run: go version
      # - name: Generate SBOM
      #   uses: anchore/sbom-action@v0
      #   with:
      #     artifact-name: bomber.cyclonedx.json
      #     path: .
      #     format: cyclonedx-json
      # - name: Release SBOM
      #   uses: anchore/sbom-action/publish-sbom@v0
      #   with:
      #     sbom-artifact-match: ".*\\.cyclonedx.json$"
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          version: ~> v2
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: sbomber
          path: dist/*
